[package]
name = "orc"
version = "0.1.0"
authors = ["Brent Kerby <blkerby@gmail.com>"]
edition = "2018"

[build-dependencies]
protoc-rust = "2.6.2"

[dependencies]
protobuf = "2.6.2"
snap = "0.2.5"
byteorder = "1.3.2"